### ISSUE TITLE
pay_sign_key指的是什么？

### ISSUE THREAD

**Issue by 990128987** [liyiorg/weixin-popular#10]
pay_sign_key指的是什么？邮箱里面没这个信息啊，谢谢~

**Comment by liyiorg** [comment]
微信支付 申请人的的邮箱获取

**Comment by 990128987** [comment]
邮箱里没看到这个，只有 partner_id和partner_key，pay_sign_key的格式大概是怎么样的？

**Comment by liyiorg** [comment]
paySignKey
公众号支付请求中用于加密的密钥Key，可验证商户唯一身份，PaySignKey
对应于支付场景中的appKey值。前三项审核通过后，在微信发送的邮件中查看

partnerId
财付通商户身份的标识。前三项审核通过后，在财付通发送的邮件中查看。
partnerKey
财付通商户权限密钥Key。前三项审核通过后，在财付通发送的邮件中查看。

**Comment by 990128987** [comment]
我明白了，微信支付V2才有paySignKey，V3就没这个了

**Comment by 990128987** [comment]
你好，有没有V3的例子？

**Comment by liyiorg** [comment]
看官方文档 用PayMchAPI 与 PayUtil
