### ISSUE TITLE
统一下单、查询订单接口都新增了version参数，希望能加入

### ISSUE THREAD

**Issue by CodinngLee** [liyiorg/weixin-popular#100]
https://pay.weixin.qq.com/wiki/doc/api/danpin.php?chapter=9_201&index=3

**Comment by liyiorg** [comment]
https://pay.weixin.qq.com/wiki/doc/api/index.html  首页中没有链接入口？

**Comment by CodinngLee** [comment]
应该没入口，直接看我发的地址
