### ISSUE TITLE
card模块中的BaseInfo对象里缺少use_all_locations参数

### ISSUE THREAD

**Issue by aroundsm** [liyiorg/weixin-popular#101]
card模块中的BaseInfo对象里缺少use_all_locations参数，可不可以加上，这个参数很早就有了
请看文档https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025283

**Comment by liyiorg** [comment]
可以

**Comment by aroundsm** [comment]
我去，果然提过这个，还是没加上啊亲
