### ISSUE TITLE
PayMchAPI.secapiPayReverse方法官方支付文档没有撤销啊

### ISSUE THREAD

**Issue by aroundsm** [liyiorg/weixin-popular#102]
PayMchAPI.secapiPayReverse方法官方文档没有撤销的，https://pay.weixin.qq.com/wiki/doc/api/micropay_sl.php?chapter=9_11&index=3
而且里面少服务商模式的参数：sub_mch_id， sub_appid
请大牛下个版本加上，感谢！

**Comment by liyiorg** [comment]
@aroundsm  下个版本更新

**Comment by liyiorg** [comment]
2.8.13 已更新

**Comment by aroundsm** [comment]
MchReverse中新增的sub_mch_id和sub_appid没有setter,getter

**Comment by liyiorg** [comment]
@aroundsm  下版本更新
