### ISSUE TITLE
发现两个小问题

### ISSUE THREAD

**Issue by caowm** [liyiorg/weixin-popular#109]
1 TemplateMessageItem没有无参构造函数

2 XMLConverUtil.convertToObject方法里面没有指定字符编码utf-8

SDK写得不错，在此感谢了！

**Comment by liyiorg** [comment]
使用方法
XMLConverUtil.convertToObject(Class<T> clazz,InputStream inputStream,Charset charset)

**Comment by caowm** [comment]
XMLConverUtil.convertToObject已经看到新版了。
TemplateMessageItem只有一个带参数的构造函数，没有无参的构造函数。在SpringMVC里面，如果显式定义了有参数的构造函数，必须定义一个无参构造函数，否则参数无法绑定。
