### ISSUE TITLE
PromotionDetailXmlAdapter问题

### ISSUE THREAD

**Issue by aroundsm** [liyiorg/weixin-popular#112]
MchPayNotify中的字段promotion_detail类型是List<PromotionDetail>，适配器PromotionDetailXmlAdapter返回的是PromotionDetail，我用xml转dojo测试了下，解析不了，应该返回List<PromotionDetail>吧？

**Comment by aroundsm** [comment]
@Override
	public List<PromotionDetail> unmarshal(String v) throws Exception {
		String a = JSON.parseObject(v).getString("promotion_detail");
		return JSON.parseArray(a, PromotionDetail.class);
	}

**Comment by liyiorg** [comment]
下版本更新
```java
public class PromotionDetailXmlAdapter extends XmlAdapter<String, List<PromotionDetail>> {

	@Override
	public List<PromotionDetail> unmarshal(String v) throws Exception {
		return JSON.parseArray(v, PromotionDetail.class);
	}

	@Override
	public String marshal(List<PromotionDetail> v) throws Exception {
		return "<![CDATA[" + JSON.toJSONString(v) + "]]>";
	}
}
```

**Comment by aroundsm** [comment]
你写的这个unmarshal(String v)方法解析不了，请参考我上面写的，我测试过的

**Comment by liyiorg** [comment]
这个版本已经发布了，只能到下个月再更新。
