### ISSUE TITLE
查询红包记录接口返回结果中领取记录未反序列化GethbinfoResult

### ISSUE THREAD

**Issue by lineng** [liyiorg/weixin-popular#113]
https://api.mch.weixin.qq.com/mmpaymkttransfers/gethbinfo
接口返回的领取记录在GethbinfoResult中未定义反序列化信息
<xml>...<hblist><hbinfo><openid><![CDATA[oHkLxtzmyHXX6FW_cAWo_orTSRXs]]></openid><amount>100</amount><rcv_time><![CDATA[2016-08-08 21:49:46]]></rcv_time></hbinfo></hblist></xml>

**Comment by liyiorg** [comment]
@lineng  请将问题做下详细说明

**Comment by liyiorg** [comment]
是要实现  java.io.Serializable 接口吗
