### ISSUE TITLE
TokenManager没有正常刷新token

### ISSUE THREAD

**Issue by NemoHoHaloAi** [liyiorg/weixin-popular#116]
初始化TokenManager之后，依然存在通过 TokenManager.getToken(wechat.appid) 获取到的token为null的情况

**Comment by liyiorg** [comment]
TokenManager 默认使用守护线程运行。可以调用  TokenManager.setDaemon(false) 修改。或者自定义调度代码 ，使用TokenAPI刷新token 。

**Comment by NemoHoHaloAi** [comment]
ths
