### ISSUE TITLE
客服功能获取基本信息 报json格式错误

### ISSUE THREAD

**Issue by maxg4810** [liyiorg/weixin-popular#117]
KFAccount getkflist = CustomserviceAPI.getkflist(at.getAccess_token());
返回的getkflist 是null的 报错json格式错误

**Comment by warthur1214** [comment]
我也遇到这个问题了。
如 @liyiorg 所说，KFAccount类里的 KF_List改为静态内部类就能解决；
我更新了fastjson的版本后也不再报错了

**Comment by liyiorg** [comment]
内部类应该定义为静态内部类，下版本修复。
