### ISSUE TITLE
com.qq.weixin.mp.aes.SHA1

### ISSUE THREAD

**Issue by clfsoft** [liyiorg/weixin-popular#119]
e.printStackTrace();没有必要吧.	

	} catch (Exception e) {
			e.printStackTrace();
			throw new AesException(AesException.ComputeSignatureError);
		}

**Comment by liyiorg** [comment]
这些都是微信官方的代码，没有特别需求的话还是别修改。

**Comment by clfsoft** [comment]
e.printStackTrace(); 把log搞的乱七八糟的啊.
要出力到文件的log,就没了啊.

**Comment by clfsoft** [comment]
最后发现这一堆代码都是来自微信的demo,程序.
demo程度的玩具代码,哪里算是什么官方代码啊.
