### ISSUE TITLE
TokenManager 和 TicketManager 有多机版么，例如基于redis

### ISSUE THREAD

**Issue by wuxudong** [liyiorg/weixin-popular#122]
当多机部署时，每台服务器都更新 accessToken， 应该会导致 出问题吧？

有基于redis的分布式版本么？

**Comment by liyiorg** [comment]
access_token 中心化管理实现的方式有很多种，所以这就不做提供了。

**Comment by wuxudong** [comment]
是让用户自行实现，是么？
那我做完后再提pull request吧，毕竟开箱即用也是很好的体验

**Comment by wuxudong** [comment]
做了一个简化的[集群demo](https://github.com/wuxudong/wechat-token-manager-cluster-demo)。 
基于 redisson 做多机数据共享
基于 shedlock 做多机并发更新的 同步问题。

代码虽然少， 但确实对外部框架依赖比较多。 不太合适作为 weixin-popular 的一部分。
但也提供出来，供有需要的人参考。
