### ISSUE TITLE
SnsApi#jscode2session 返回值中貌似没有包含 unionId

### ISSUE THREAD

**Issue by JasonWangex** [liyiorg/weixin-popular#124]
Jscode2sessionResult 中只看到了 openid, session_key
参考 https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-login.html#wxloginobject
”code 换取 session_key“ 中返回参数

**Comment by liyiorg** [comment]
下版本  2.8.16 中添加

**Comment by thetcc** [comment]
我也需要这个字段

**Comment by liyiorg** [comment]
还未提交到maven 仓库，代码已提交到github,着急的可以下载打包到本地maven 仓库
