### ISSUE TITLE
商户支付接口PayMchAPI.mmpaymkttransfersPromotionTransfers签名错误问题

### ISSUE THREAD

**Issue by declan94** [liyiorg/weixin-popular#125]
调用此接口微信返回签名错误，检查源码发现签名时没有将sign_type字段移除，在微信的接口定义中没有此字段。https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2

所以只有当sign_type设置为null时签名才正确，否则签名就错误了。

**Comment by liyiorg** [comment]
企业付款仅支持默认的 MD5 签名方式

https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2

文档中未包含 sign_type 。

SDK 中的sign_type 作为预留字段，暂不支持该接口。
