### ISSUE TITLE
大神讲解下为啥直接调发红包接口返回空啊。。。服务器上也需要安装证书吗

### ISSUE THREAD

**Issue by zjh02249** [liyiorg/weixin-popular#128]
参数都弄好了 ，商户平台也配置了，但是返回空 但是就算是错的 总该有返回提示吧。。。
求教ing

**Comment by liyiorg** [comment]
https://github.com/liyiorg/weixin-popular/wiki/%E8%AE%BE%E7%BD%AEAPI%20MCH%20KeyStore

参考下
