### ISSUE TITLE
查询红包记录GethbinfoResult->hblist 获取为NULL

### ISSUE THREAD

**Issue by qiuxuhao** [liyiorg/weixin-popular#129]
查询红包记录返回的XML信息中hblist字段无法正常转换获取时为空

**Comment by liyiorg** [comment]
@qiuxuhao  返回的xml 信息粘贴出来，看一下是什么问题

**Comment by qiuxuhao** [comment]
@liyiorg 
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<result_code><![CDATA[SUCCESS]]></result_code>
<err_code><![CDATA[SUCCESS]]></err_code>
<err_code_des><![CDATA[OK]]></err_code_des>
<mch_billno><![CDATA[*****]]></mch_billno>
<mch_id><![CDATA[*****]]></mch_id>
<detail_id><![CDATA[*****]]></detail_id>
<status><![CDATA[RECEIVED]]></status>
<send_type><![CDATA[API]]><nd_type>
<hb_type><![CDATA[NORMAL]]><_type>
<total_num>1</total_num>
<total_amount>100</total_amount>
<send_time><![CDATA[2017-12-06 17:45:32]]><nd_time>
<hblist>
<hbinfo>
<openid><![CDATA[ojptqt6AA3rmLM2_-Eyhtmvg1TJA]]></openid>
<amount>100<ount>
<rcv_time><![CDATA[2017-12-06 17:47:26]]></rcv_time>
<info>
<list>
</xml>

本地暂时是将GethbinfoResult-》hblist 修改成如下使用的，如是本人错误使用导致望回复告知，谢谢
  @XmlElement(name = "hblist")
  private Hbinfos hbinfos;
===========
@XmlAccessorType(XmlAccessType.FIELD)
public class Hbinfos {
  @XmlElement(name = "hbinfo")
  List<Hbinfo> hbList;

  public List<Hbinfo> getHbList() {
    return hbList;
  }

  public void setHbList(List<Hbinfo> hbList) {
    this.hbList = hbList;
  }
}
=========
@XmlAccessorType(XmlAccessType.FIELD)
public class Hbinfo {
  private String openid;
  private Integer amount;
  private String rcv_time;

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public String getRcv_time() {
    return rcv_time;
  }

  public void setRcv_time(String rcv_time) {
    this.rcv_time = rcv_time;
  }
}
=======

**Comment by liyiorg** [comment]
@qiuxuhao  GethbinfoResult 中字段定义错误，这几天会修复发布一个版本。
