### ISSUE TITLE
TokenManager   TicketManager 中的map不是线程同步的,会不会有问题?

### ISSUE THREAD

**Issue by javaliquan** [liyiorg/weixin-popular#13]

**Comment by liyiorg** [comment]
单例模式，没有线程同步的问题。

**Comment by javaliquan** [comment]
在访问量大的时候,有可能出现线程问题吧,如果刚刚好在你设置的时候使用put覆盖上前的ticket,取的时候会出现问题吧,里面去算hash什么应该会出问题的吧?

**Comment by liyiorg** [comment]
一个token 要等待118分钟后才会刷新，新的token 产生后，原来的 token 在几秒钟之内还能正常调用。每次使用token 时使用 TokenManager.getToken  就不会有问题。

**Comment by javaliquan** [comment]
我的疑问是因为我们getToken是用map实现的,然后设置的时候调用的是SET,因为用的map的实现是线程的不同步的,应该改成线程同步的就没有问题了.

**Comment by liyiorg** [comment]
你可以调用 TokenAPI 手动刷新token，记录上一次老的token，当新的token产生后，原来的token在几秒钟内是能正常使用的，如果验证成功，就没有同步map的必要了。

**Comment by x03570227** [comment]
启动的时候调用了以下代码

```java
TokenManager.init(AppConst.getConfig("wx.appid"), AppConst.getConfig("wx.secret"));
TicketManager.init(AppConst.getConfig("wx.appid"));
```

但是在调用 `` TicketManager.getDefaultTicket()`` 的时候总是报NullException错误

```
java.lang.NullPointerException
	weixin.popular.support.TicketManager.getDefaultTicket(TicketManager.java:70)
```

ticket 和 token 的获取都需要在 timer 调用后才可以，而且 ticket 依赖于 token，另外，如果 appid 及相关参数都正确的情况下，因为一些原因，导致 token 不能获取到，也无法正确缓存 token 和 ticket，这种情况下，怎么保证获取 token 或 ticket 时能够重新去微信获取一次？

**Comment by liyiorg** [comment]
为了确保TokenManager 先调用，TicketManager 的init 会延迟一秒后执行。TicketManager.getDefaultTicket 应该在初始化2秒后再调用比较合适。
关于一些其它 原因导致的token 无法获取，timer 中没有做处理。除网络异常，正常情况下都是可用的。
