### ISSUE TITLE
关于JsUtil.generateConfigJson返回的字符串不符合json格式（还是就是这样的）

### ISSUE THREAD

**Issue by zjh02249** [liyiorg/weixin-popular#139]
返回的字段是不是需要自己处理呀，页面jquery直接获取到后，会报错，说格式不对。

**Comment by liyiorg** [comment]
返回的是一个javascript 对象数据，网页中申明一个对象接收即可。例如
var my_configJson =     // JsUtil.generateConfigJson 返回的文本数据。
