### ISSUE TITLE
下载对账单缺少压缩账单tar_type参数

### ISSUE THREAD

**Issue by CodinngLee** [liyiorg/weixin-popular#142]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_6

**Comment by liyiorg** [comment]
https://github.com/liyiorg/weixin-popular/tree/dev

你试下开发版本，已添加字段。我这边没有商户号，所以无法确定 tar_type 设置为GZIP 后的返回数据

**Comment by CodinngLee** [comment]
还是不行，没效果，还是返回了原来的账单字符串

**Comment by liyiorg** [comment]
这个接口内将获取到的 GZIP 流解压了

**Comment by CodinngLee** [comment]
明白，那应该就是可行了
