### ISSUE TITLE
关于使用TokenManager token 和TicketManager ticket 自动刷新会出现token过期

### ISSUE THREAD

**Issue by zjh02249** [liyiorg/weixin-popular#144]
过程中发现，再获取ticket中，会出现{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest hint: [AOs7wA0667a458!]"} ，这是自动获取的access_token过期了的问题吗，我是按照TokenManager token中弄的

**Comment by zjh02249** [comment]
会不会是一开始没有让tokenmanager先执行。。。但这样的话，为什么一开始可以行呢

**Comment by liyiorg** [comment]
检查下token 刷新日志，看是否正常刷新了
ACCESS_TOKEN refurbish with appid

**Comment by zjh02249** [comment]
ACCESS_TOKEN 我看日志是刷新了，08:04:22.582 [pool-39-thread-1] INFO  weixin.popular.support.TokenManager - ACCESS_TOKEN refurbish with appid:wxf9c79f55a781b8b4，但是在获取ticket时，就报这个错了
![image](https://user-images.githubusercontent.com/18898962/38180714-2cccde56-3661-11e8-85e6-bae7a413a88e.png)
08:24:27 那一条报这个错
emmm。。
我把
`  // TicketManager.init(ConfUtil.getProperty("appid"));
       TicketManager.init(ConfUtil.getProperty("appid"), 5, 60 * 119);`
两句都用上了。。
是我搞错了。。。

**Comment by Android-BRUCE** [comment]
可能是我初始化没设置监听器的顺序，现在设置了下顺序，我再试试
