### ISSUE TITLE
ComponentAPI.componentloginpage增加auth_type参数

### ISSUE THREAD

**Issue by wuyifan** [liyiorg/weixin-popular#146]
官方的API “componentloginpage”中针对小程序授权，增加了一个auth_type参数，
ComponentAPI.componentloginpage函数中还没有对应增加。

参见：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN

**Comment by liyiorg** [comment]
下个版本添加， 建议你这边使用以下方式调用。
```java
ComponentAPI.componentloginpage("component_appid&auth_type=1","pre_auth_code","redirect_uri");
```

**Comment by wuyifan** [comment]
ComponentAPI.api_get_authorizer_info 获取小程序的基本信息的返回内容和公众号也有区别，多了几个字段，请一起加上吧。
还是参见上面那个地址。
