### ISSUE TITLE
企业微信的相关api

### ISSUE THREAD

**Issue by warthur1214** [liyiorg/weixin-popular#149]
企业微信的相关api有支持的可行性吗？

**Comment by liyiorg** [comment]
企业微信 可归为另一大类接口，其中也有第三方平台等。看过相关的文档，由于目前业务中并未用到，未做接口包装。 可以参照 weixin-popular 的代码，另建一个企业微信专用SDK . 企业微信中的太多数接口包装都能在weixin-popular  中找到参照。
