### ISSUE TITLE
少字段

### ISSUE THREAD

**Issue by aroundsm** [liyiorg/weixin-popular#150]
weixin.popular.bean.card.BaseInfo中少个字段
@JSONField(name = "use_all_locations")
private Boolean useAllLocations;//设置本卡券支持全部门店，与location_id_list互斥

**Comment by liyiorg** [comment]
@aroundsm  卡卷这一块的接口由开发者 @Moyq5  贡献的代码，如果你了解这一块的接口并有开源的意愿，可以提交代码更新！

**Comment by liyiorg** [comment]
@aroundsm  该字段会在 2.8.20 版本中添加
