### ISSUE TITLE
bean目录下的基础对象是否可以支持序列化?

### ISSUE THREAD

**Issue by FjcD** [liyiorg/weixin-popular#152]
基础对象不能序列化,dubbo调用的时候出问题了,是否支持下?

**Comment by liyiorg** [comment]
@FJCDrome   这方面有考虑过，但最终还是决定不加！原因为以下几点：
1、bean 包下的类数量已很大
2、加上序列化后的新版本，不确定会不会对已使用到生产环境的服务产生影响。
3、dubbo 调用直接使用bean 包下类的场景应该不多，可以通过继承类或纯字符参数处理。
