### ISSUE TITLE
获取用户基本信息的接口实体类User少字段

### ISSUE THREAD

**Issue by zh1181500972** [liyiorg/weixin-popular#154]
缺少微信的这几个字段

subscribe_scene | 返回用户关注的渠道来源，ADD_SCENE_SEARCH 公众号搜索，ADD_SCENE_ACCOUNT_MIGRATION 公众号迁移，ADD_SCENE_PROFILE_CARD 名片分享，ADD_SCENE_QR_CODE 扫描二维码，ADD_SCENEPROFILE LINK 图文页内名称点击，ADD_SCENE_PROFILE_ITEM 图文页右上角菜单，ADD_SCENE_PAID 支付后关注，ADD_SCENE_OTHERS 其他
-- | --
qr_scene | 二维码扫码场景（开发者自定义）
qr_scene_str | 二维码扫码场景描述（开发者自定义）

**Comment by liyiorg** [comment]
@zh1181500972  下个版本  2.8.20 中添加
