### ISSUE TITLE
JsUtil.generateConfigJson 生成的json不规范

### ISSUE THREAD

**Issue by dudulabubu** [liyiorg/weixin-popular#156]
![image](https://user-images.githubusercontent.com/5857946/41408323-e0ed97cc-7004-11e8-90be-8f0c13cd5743.png)
![image](https://user-images.githubusercontent.com/5857946/41408331-e5d9cf30-7004-11e8-94ad-f56afe20619b.png)

**Comment by liyiorg** [comment]
@sqzr  这是一个 Javascript 对象，不用做 json 解析，直接使用。
