### ISSUE TITLE
XMLConverUtil.convertToMap（）方法存在漏洞

### ISSUE THREAD

**Issue by LinSheng0719** [liyiorg/weixin-popular#159]
微信支付SDK XXE漏洞
https://blog.csdn.net/u013224189/article/details/80902339
官方WxPayAPI_JAVA_v3 发现了该漏洞，发现这边也存在

**Comment by EarnestLee** [comment]
我也收到这通知了，麻烦作者修复下哦

**Comment by chenmins** [comment]
彼此彼此，刚接到通知

**Comment by chenmins** [comment]
https://blog.csdn.net/aitangyong/article/details/51907064

**Comment by chenmins** [comment]
https://blog.csdn.net/aitangyong/article/details/51907064 参考这个

**Comment by liyiorg** [comment]
周六前  会发布一个更新版本

**Comment by EarnestLee** [comment]
发版具体时间是啥时候呢，商户平台打电话说我们有潜在风险，需要尽快修复。

**Comment by liyiorg** [comment]
@EarnestLee  今天发版  明天可从maven 中央仓库提取
