### ISSUE TITLE
MCH支付成功通知时，SignatureUtil.validateAppSignature(payNotify,key)产生的签名不一致

### ISSUE THREAD

**Issue by free89** [liyiorg/weixin-popular#16]
MchPayNotify继承MchBaseResult，只是Map<String,String> map = MapUtil.objectToMap(payNotify)这里产生的map是不包括MchBaseResult里面的变量

**Comment by liyiorg** [comment]
@free89  2.4.2-RELEASE 中bug 已修复！感谢反馈问题。
