### ISSUE TITLE
PayUtil签名获取nonce_str有Bug

### ISSUE THREAD

**Issue by chenshukun7** [liyiorg/weixin-popular#162]
map.put("nonce_str", UUID.randomUUID().toString().replace("-", ""));
replace("-", "")方法只能替换一次字符"-"，UUID其他的字符"-"没有被替换成""，导致nonce_str长度过长。
应将replace()改为replaceAll("-", "")

**Comment by liyiorg** [comment]
有这种情况发生！确认使用的jdk 版本是 1.7 以上吗？

**Comment by chenshukun7** [comment]
1.6
