### ISSUE TITLE
公众号支付中，下载对账单部分无法使用

### ISSUE THREAD

**Issue by free89** [liyiorg/weixin-popular#17]
报Content is not allowed in prolog.]错误

**Comment by liyiorg** [comment]
更新到 2.4.3 试一下

**Comment by free89** [comment]
依然报这个错误，返回数据参考：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_6

**Comment by liyiorg** [comment]
@free89  更新到2.4.4
调用示例 
https://github.com/liyiorg/weixin-popular/wiki/%E5%AF%B9%E5%B8%90%E5%8D%95%E8%B0%83%E7%94%A8%E7%A4%BA%E4%BE%8B
