### ISSUE TITLE
获取微信授权数据时，会出现fastjson转换错误

### ISSUE THREAD

**Issue by evanyangg** [liyiorg/weixin-popular#178]
com.alibaba.fastjson.JSONException: syntax error, expect {, actual int, pos 1, fastjson-version 1.2.49
![image](https://user-images.githubusercontent.com/22952321/46071606-001ce300-c1b3-11e8-845c-bcf8dbd07edf.png)
必现场景是新用户首次授权时解密数据会出现。
授权过之后再次授权解密数据正常。

**Comment by liyiorg** [comment]
传入的参数 encryptedData 数据格式不对吧。

**Comment by evanyangg** [comment]
![image](https://user-images.githubusercontent.com/22952321/46240491-0392b300-c3db-11e8-9473-6a2c065b3b9c.png)
找到这个问题的原因了， 这里的data返回回来的是乱码，所以出现了问题
@liyiorg

**Comment by evanyangg** [comment]
不好意思，第一次接触小程序，我的session_key 没有和微信服务的session_key 保持一致，所以解密的时候出现了问题。会继续支持的，加油！
