### ISSUE TITLE
wx.config配置问题

### ISSUE THREAD

**Issue by wcp1230** [liyiorg/weixin-popular#18]
String jsapi_ticket = TicketManager.getTicket(appId);
String configjson = JsUtil.generateConfigJson(jsapi_ticket, false, appId, url, jsApiList);

调用上面方法返回的configjson，直接配置 wx.config(configjson)，提示'config:fail'错误,怎么解决此问题

**Comment by liyiorg** [comment]
1、将debug 模式打开
2、确定提交的url参数正确，url为完整路径，包含路径后的参数。
