### ISSUE TITLE
SnsAPI.oauth2AccessToken 结果一直是40029，invalid code

### ISSUE THREAD

**Issue by luowenyue** [liyiorg/weixin-popular#185]
调用SnsAPI.oauth2AccessToken获取SnsToken 返回值一直是40029 ，invalid code
目前可以确保wxAppId wxAppSecret 以及授权code正确
搜索得知微信会做302重定向 但我调试发现每次请求都是40029
如果微信做了重定向按道理说这个库获取肯定会报40029的，为何没人提issues？ 
是做了什么处理么，但是没看出来 望告知

**Comment by an9xyz** [comment]
看看code是不是重复使用了

**Comment by luowenyue** [comment]
嗯 仔细看了官方文档 是我自己理解错误 抱歉
