### ISSUE TITLE
LocalHttpClient.initMchKeyStore在什么时候被调用

### ISSUE THREAD

**Issue by hesling** [liyiorg/weixin-popular#19]
LocalHttpClient.initMchKeyStore在什么时候被调用

**Comment by liyiorg** [comment]
微信支付中 的退款、红包等API需要双向安全认证。LocalHttpClient.initMchKeyStore的作用是初始化相应的HttpClient,在程序初始化的时候调用一次即可。如果没有使用PayMchAPI 中退款等功能，不用调用该方法。

**Comment by hesling** [comment]
好的，谢谢
