### ISSUE TITLE
bug 对象 SecapiPayProfitsharingfinishResult缺少注解

### ISSUE THREAD

**Issue by a497771654** [liyiorg/weixin-popular#210]
public class SecapiPayProfitsharingfinishResult

缺少注解
@XmlRootElement(
        name = "xml"
)
@XmlAccessorType(XmlAccessType.FIELD)
解析xml报错
javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"xml"). Expected elements are (none)

**Comment by a497771654** [comment]
这个注解不加一下吗？要不这个类解析不了xml

**Comment by liyiorg** [comment]
@a497771654   请使用 2.8.30 版本
