### ISSUE TITLE
unifiedorderResult.getPrepay_id() = null 怎么处理??

### ISSUE THREAD

**Issue by summerwxy** [liyiorg/weixin-popular#22]
// 统一下单，生成预支付订单
UnifiedorderResult unifiedorderResult = PayMchAPI.payUnifiedorder(unifiedorder,key);
String json = PayUtil.generateMchPayJsRequestJson(unifiedorderResult.getPrepay_id(), appid, key);

我运行的时候 unifiedorderResult.getPrepay_id() 取得 null, 应该怎么除错 ??

**Comment by summerwxy** [comment]
我自己在 UnifiedorderResult 里面加上 底下这段 就可以看到错误原因了

----------------------------------------------------------------------
	@XmlElement
	@XmlJavaTypeAdapter(value = AdaptorCDATA.class)
	private String return_code;

	public String getReturn_code() {
		return return_code;
	}

	public void setReturn_code(String return_code) {
		this.return_code = return_code;
	}


	@XmlElement
	@XmlJavaTypeAdapter(value = AdaptorCDATA.class)
	private String return_msg;

	public String getReturn_msg() {
		return return_msg;
	}

	public void setReturn_msg(String return_msg) {
		this.return_msg = return_msg;
	}


----------------------------------------------------------------------

**Comment by yannxia** [comment]
你可以提交一个Pull Request

**Comment by liyiorg** [comment]
@yannxia 这个类继承 MchBase，已经包含相关字段。
