### ISSUE TITLE
建议User.qr_scene使用Long类型，最近生产环境因为这个字段报错，仔细查了下，Integer并不能兼容临时二维码32位的场景，导致强转报错，望采纳。

### ISSUE THREAD

**Issue by hkkFun** [liyiorg/weixin-popular#221]
建议User.qr_scene使用Long类型，最近生产环境因为这个字段报错，仔细查了下，Integer并不能兼容临时二维码32位的场景，导致强转报错，望采纳。
![image](https://user-images.githubusercontent.com/17877428/70323868-f2f48d00-1868-11ea-9390-fcd60f90cf76.png)

**Comment by liyiorg** [comment]
该字段目前暂不做调整，建议生成字符串值类型的临时二维码。
```java
QrcodeAPI.qrcodeCreateTemp(String access_token,int expire_seconds,String scene_str)
```

**Comment by liyiorg** [comment]
或者使用不大于Int 最大值创建。
```java
QrcodeAPI.qrcodeCreateTemp(String access_token,int expire_seconds,long scene_id)
```

**Comment by hkkFun** [comment]
嗯，现在已经换字符串类型了。
