### ISSUE TITLE
在应用中使用了TokenManager.getToken(appid);保存了access_token,之后再另一个地方使用SnsAPI.oauth2AccessToken

### ISSUE THREAD

**Issue by miws** [liyiorg/weixin-popular#226]
在应用中使用了TokenManager.getToken(appid);保存了access_token,之后再另一个地方为了获取用户信息使用了SnsAPI.oauth2AccessToken, 导致前一个保存的access_token失效,应该如何处理?

**Comment by liyiorg** [comment]
每次要使用token 都调用 TokenManager.getToken(appid);  获取，不要保存。

**Comment by miws** [comment]
> 每次要使用token 都调用 TokenManager.getToken(appid); 获取，不要保存。

这样调用频次太高了, 不够使用啊
