### ISSUE TITLE
是否可以基于Spring做一个微服务

### ISSUE THREAD

**Issue by yannxia** [liyiorg/weixin-popular#24]
是不是能够在此基础上，使用Spring Boot制作一个快速使用的完整项目？不知道您有没有这个计划。
@liyiorg

**Comment by liyiorg** [comment]
weixin-popular 是根据官方文档，按一定的API命名规则创建的SDK，依赖少量的jar包。包含的API并不是所有项目都需要的，可以根据自身项目的需求，选择调用合适的API。建议开发者开发之前看下官方文档，了解下有哪些接口功能可用！
