### ISSUE TITLE
关于使用企业付款时的OPENID_ERROR问题

### ISSUE THREAD

**Issue by melonlee** [liyiorg/weixin-popular#27]
请问在使用PayMchAPI的mmpaymkttransfersPromotionTransfers时有没有遇到OPENID_ERROR (openid和appid不匹配)的问题 :）

我在使用时已确保该openid账号已经关注了该公众账号，调用代码如下，但是一直提示OPENID_ERROR (openid和appid不匹配)

		Transfers transfers = new Transfers();
 
		transfers.setMch_appid("wx9d154566xxxxxxx");
		transfers.setMchid("xxxxxxxxx");
		transfers.setOpenid("olEows2vTZxKZ6z3eavTDsfOky5k");
		transfers.setNonce_str(MRandomUtils.generateString(32));
		transfers.setPartner_trade_no(MDateUtils.generateOrderNO());
		transfers.setCheck_name("NO_CHECK");
		transfers.setAmount("100");
		transfers.setDesc("约会退款");
		transfers.setSpbill_create_ip("xx.xx.xx.xx");

		LocalHttpClient.initMchKeyStore("12345678", p12_file);
		
		TransfersResult result = PayMchAPI.mmpaymkttransfersPromotionTransfers(
				transfers, key);

多谢!

**Comment by liyiorg** [comment]
LocalHttpClient.initMchKeyStore("12345678", p12_file);
只需要设置一次

transfers.setMchid("xxxxxxxxx") 应该与 initMchKeyStore 中的 mch_id 一致

**Comment by melonlee** [comment]
犯了很低级的错误，把APP支付平台的商户号当做了H5支付的商户号 :(  thx! @liyiorg  ：）
