### ISSUE TITLE
连续调用任何API方法，第二次调用都报fail to respond

### ISSUE THREAD

**Issue by neillam** [liyiorg/weixin-popular#33]
两次微信接口调用之间如果间隔超过2秒，都能成功返回。如果第一次和第二次间隔时间很短，第二次就会报org.apache.http.NoHttpResponseException: api.weixin.qq.com:443 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
从1月7日起出现这个情况。
请问是什么原因？

**Comment by liyiorg** [comment]
说明下具体调用的接口

**Comment by duanxiangdong** [comment]
微信支付的接口,如果在同时间多次请求,偶尔会出现org.apache.http.NoHttpResponseException: api.mch.weixin.qq.com:443 failed to respond的问题
