### ISSUE TITLE
没注释看的头疼

### ISSUE THREAD

**Issue by x7LoveLin** [liyiorg/weixin-popular#36]
以前版本也是用你这个 挺好用的，以前版本有方法注释 怎么现在都没了呢。

**Comment by x7LoveLin** [comment]
发红包是要携带证书的 ，请问证书怎么传过去 。

**Comment by liyiorg** [comment]
可能打包到maven 中央仓库的时候自动去除了注释。
以下为证书设置
https://github.com/liyiorg/weixin-popular/wiki/%E8%AE%BE%E7%BD%AEAPI%20MCH%20KeyStore

**Comment by x7LoveLin** [comment]
作者大大 调用 XMLConverUtil遇到  java.lang.NoClassDefFoundError: com/sun/xml/bind/marshaller/CharacterEscapeHandler

**Comment by liyiorg** [comment]
检查jdk 版本(7+) ，并将 weixin-popular pom.xml 中的依赖位置放到最上面。
