### ISSUE TITLE
上传视频乱码，以及视频过大无法上传

### ISSUE THREAD

**Issue by zuihou** [liyiorg/weixin-popular#38]
1，MaterialAPI.add_material 方法上传的视频，会出现乱码。
multipartEntityBuilder.addTextBody("description", JsonUtil.toJSONString(description)); 改为multipartEntityBuilder.addTextBody("description", JsonUtil.toJSONString(description), ContentType.create("text/plain", CHARSET_UTF8));    之后 才正常显示。

2，上传几百k的视频没问题， 但是上传手机拍摄的mp4，视频大小为1.5M 1秒， 4M 2秒， 9M 4秒 ， 15M 11秒 均报错：
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)

**Comment by liyiorg** [comment]
超时设置 LocalHttpClient .setTimeout(5000); 默认5秒。大文件上传，超时也要设置长一点。
