### ISSUE TITLE
上次merge/push时候没有解决好冲突

### ISSUE THREAD

**Issue by hywang1985** [liyiorg/weixin-popular#40]
请参照API包里的文件。谢谢。

**Comment by hywang1985** [comment]
这次commit没有合并好。
https://github.com/liyiorg/weixin-popular/commit/0fcc780e9b172573a2f8bf4e77b8b4e781c98788

**Comment by hywang1985** [comment]
另外我发现除了tokenManager以外又多了一套Token api. 是不是重复了？
由Moyq5贡献的，请看包weixin.popular.support.token下的代码。

**Comment by liyiorg** [comment]
上次合并的代码有点问题，未做处理，源码研究，使用 2.8.0 tag 的版本。
