### ISSUE TITLE
PayUtil.generateMchPayJsRequestJson生成的timeStamp字段有问题

### ISSUE THREAD

**Issue by hywang1985** [liyiorg/weixin-popular#42]
微信支付请求新版在JSSDK端要求timestamp必须是全小写。
而PayJsRequest对象里的timeStamp是驼峰式命名法。

参考下列微信文档：

wx.chooseWXPay({
    timestamp: 0, // 支付签名时间戳，注意微信jssdk中的所有使用timestamp字段均为小写。但最新版的支付后台生成签名使用的timeStamp字段名需大写其中的S字符
    nonceStr: '', // 支付签名随机串，不长于 32 位
    package: '', // 统一支付接口返回的prepay_id参数值，提交格式如：prepay_id=***）
    signType: '', // 签名方式，默认为'SHA1'，使用新版支付需传入'MD5'
    paySign: '', // 支付签名
    success: function (res) {
        // 支付成功后的回调函数
    }
});

**Comment by liyiorg** [comment]
PayUtil.generateMchPayJsRequestJson 生成的JSON 对应的JS调用方式
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_7&index=6

**Comment by liyiorg** [comment]
JsUtil.generateChooseWXPayJson 生成JS 的调用JSON, 目前的代码是老的方式，将于最近几日 2.8.1 中更新。
