### ISSUE TITLE
关于BaseAPI中getATPN方法

### ISSUE THREAD

**Issue by butterflyjzf** [liyiorg/weixin-popular#45]
方法中return值为return "access_token" or "authorizer_access_token"
但是对于第三方模式下，貌似参数也是"access_token",并非 "authorizer_access_token"
@liyiorg

**Comment by liyiorg** [comment]
使用 API.defaultMode(mode); 设置默认模式，使用API.mode(mode)  设置于当前线程环境下的API模式。

**Comment by butterflyjzf** [comment]
额，我描述不太清除~意思是第三方平台时，微信接口里传入authorizer_access_token这个参数会报错

**Comment by aroundsm** [comment]
是的，我这几天也被这个坑了，官方文档说的很模糊，我一直以为第三方代替公众号调用的参数名是authorizer_access_token，搜索了好多，确认参数名和普通模式一样，也应该是access_token

**Comment by aroundsm** [comment]
所以不管你是直接公众号调用还是第三方授权公众号调用都用默认api模式就好了，否则调用接口会报access_token missing

**Comment by liyiorg** [comment]
哦，我这没有第三方平台的账号。那不要使用API 类即可，默认使用access_token 作为参数名。

**Comment by menng** [comment]
这个地方确实与普通的参数名一样，我最近也在做一个第三方平台。不是authorizer_access_token，就是默认的access_token
