### ISSUE TITLE
发现ApiGetAuthorizerInfoResult类中的bug

### ISSUE THREAD

**Issue by zuihou** [liyiorg/weixin-popular#46]
weixin.popular.bean.component.ApiGetAuthorizerInfoResult  类中有个 qrcode_url 字段，应该是属于Authorizer_info 中的字段。 

微信文档那边就写错了。所以按你现在ApiGetAuthorizerInfoResult  中的写法是拿不到值的。

**Comment by liyiorg** [comment]
好的，qrcode_url  将移到 Authorizer_info 中
