### ISSUE TITLE
setBody中文导致签名错误的解决方法

### ISSUE THREAD

**Issue by woaer** [liyiorg/weixin-popular#50]
看了#20 #11 的提问，发现问题还是没解决。

自己在调试中发现是 `weixin.popular.util.SignatureUtil` 这个class 下边的签名方法所致

``` java
/**
     * 生成sign MD5 加密 toUpperCase
     * @param map map
     * @param paternerKey paternerKey
     * @return sign
     */
    public static String generateSign(Map<String, String> map,String paternerKey){
        Map<String, String> tmap = MapUtil.order(map);
        if(tmap.containsKey("sign")){
            tmap.remove("sign");
        }
        String str = MapUtil.mapJoin(tmap, false, false);
        return DigestUtils.md5Hex(str+"&key="+paternerKey).toUpperCase();
    }
```

修改如下：
`DigestUtils.md5Hex(str+"&key="+paternerKey)` => `DigestUtils.md5Hex((str+"&key="+paternerKey).getBytes("UTF-8"))`

希望 @liyiorg 在下个版本解决下。

**Comment by liyiorg** [comment]
@jiklin  你这也是在统一下单时出现的错误吗？

**Comment by woaer** [comment]
@liyiorg 是的，`PayMchAPI.payUnifiedorder(...)`中文会报签名错误。

**Comment by liyiorg** [comment]
@jiklin  看了下 DigestUtils.md5Hex(String str)  源码，默认转为UTF-8 字节组。很多开发者统一下单中文名称都是没有问题的，你检查下commons-codec-1.6.jar 依赖的版本是不是一致。

**Comment by rockshark2046** [comment]
@liyiorg windows server 2012 PayMchAPI.payUnifiedorder(...)中文会报签名错误。commons-codec-1.4.jar替换为commons-codec-1.6.jar不再报错。
