### ISSUE TITLE
TokenAPI.token()获取不到token

### ISSUE THREAD

**Issue by yangqinglei26** [liyiorg/weixin-popular#53]
TokenAPI.token()获取不到token---》
应该使用get请求

**Comment by usenrong** [comment]
jsapi_ticket也有类似问题,但是之前POST也能获取到，最近两天似乎不行了 获取Token经常报40002

**Comment by justinxguo** [comment]
curl -X "POST" -v  "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=***************&secret=************************"

我使用curl工具提交post请求都没问题，然后使用java库就这两天有问题，不知是不是微信做了什么限制。

**Comment by liyiorg** [comment]
请求post 方法要改为get 方法，微信官方api 后台做了调整。我这两天将更新一个新版本。
