### ISSUE TITLE
在maven中央仓库下载的2.8.0有问题

### ISSUE THREAD

**Issue by zggg** [liyiorg/weixin-popular#56]
第三方API ComponentAPI  里面用的全是BASE_URI
应该是MP_URI

**Comment by liyiorg** [comment]
确定你看的是这个官方文档吗？
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN

目前最新版本为 2.8.1
