### ISSUE TITLE
ticket刷新

### ISSUE THREAD

**Issue by cpa519904** [liyiorg/weixin-popular#62]
/**
	 * 初始化ticket(jsapi) 刷新，每119分钟刷新一次。<br>
	 * 依赖TokenManager
	 * @param appid appid
	 */
	public static void init(final String appid){
		init(appid,0,60*119);
	}

 这里刷新 为什么是119分钟  微信不是 文档不是说7200秒么  是我理解有吴还是什么问题

**Comment by liyiorg** [comment]
如果刚好7200 秒 刷新可能会有误差，所以刷新时间要小于7200 秒。

**Comment by cpa519904** [comment]
初始化token 刷新，每118分钟刷新一次。 TokenManager 这个方法  你写的固定的
这个我自己可以修改么   118分钟刷新一下次   可以修改为7000秒刷新一次么

**Comment by cpa519904** [comment]
顺便 请教个问题   微信签名  浏览器地址中有特殊符号的怎么处理  我发现 从QQ分享到微信的  地址栏目 ?，空格 .. 特殊符号 变了

**Comment by liyiorg** [comment]
init 方法有多个重载，可以满足自定义刷新时间间隔。
使用微信JS 自定义分享内容及地址。
