### ISSUE TITLE
守护线程 自动清理过期key ，间隔时间60秒,怎样支持集群部署应用?

### ISSUE THREAD

**Issue by mnshun** [liyiorg/weixin-popular#65]

**Comment by liyiorg** [comment]
使用 redis  支持     

JedisExpireKey  或自定义实现 ExpireKey

**Comment by mnshun** [comment]
我最近在做微信卡券相关的业务，对被动接收事件和微信卡券自己添加了些东西，能不能借助你的开源项目，共享出来。

**Comment by liyiorg** [comment]
可以自建开源项目，将weixin-popular作为依赖。
