### ISSUE TITLE
微信接收消息的类型或事件是类型，有封装么？

### ISSUE THREAD

**Issue by dulinanaaa** [liyiorg/weixin-popular#66]
如题，微信接收消息的类型或事件是类型，在代码中有相应的类进行封装么？具体在哪个包下啊？
昨天刚开始用，接收了几种类型的消息，image,text等，不知道有没有写好的类。还是说自己手动给封装一下啊？
别外，还有好多api，文档比较少

**Comment by liyiorg** [comment]
api  文档看微信官方文档，消息类型或事件自定义实现。
