### ISSUE TITLE
weixin-popular中的微信退款接口需要证书吗

### ISSUE THREAD

**Issue by yf-sky** [liyiorg/weixin-popular#68]
您好，微信官方文档中退款api需要证书，请问调用您写的退款接口需要证书吗，如果需要怎么传？

**Comment by liyiorg** [comment]
https://github.com/liyiorg/weixin-popular/wiki/%E8%AE%BE%E7%BD%AEAPI%20MCH%20KeyStore

**Comment by yf-sky** [comment]
谢谢您的解答！

**Comment by yf-sky** [comment]
您好，我遇到了一个新问题。
我们的微信支付和退款都是子账户挂在主账户上用的，所以传入参数有mch_id,sub_mch_id等，而且我现在用的退款证书是子微信账户的，所以我初始化证书的时候是这样的，因为子账户sub_mch_id才能作为证书密码：
 LocalHttpClient.initMchKeyStore(secapiPayRefund.getMch_id(), "keyStoreFilePath");
但是当我发起退款时，您写的接口中获取localhttp的方法是这样的：
T t = httpClient_mchKeyStore.get(mch_id).execute(request,responseHandler,HttpClientContext.create());
这个时候httpClient_mchKeyStore.get(mch_id)为null，报错了。

请问有办法解决吗？

**Comment by liyiorg** [comment]
@yf-sky  是使用服务商对应mch_id 的证书吧，我这没服务商的号，无法证实其可用性。
