### ISSUE TITLE
关于统一下单中detail的问题

### ISSUE THREAD

**Issue by DemonTang** [liyiorg/weixin-popular#69]
@liyiorg 你好，我在统一下单时遇到了如下问题：
我把detail相关信息增加到里面之后微信端提示有误，然后我去掉detail信息就又可以了。
所以想问下这个detail信息中参数是否有误，或者是detail中字段的来源是从哪儿获知的，我在微信开发文档中没有找到这块的描述。
因为微信扫码时就提示的是参数有问题。
麻烦解答下，谢谢

**Comment by liyiorg** [comment]
统一下单 PayMchAPI.payUnifiedorder 中未对detail字段做签名处理。会导致签名错误，下版本修复。

**Comment by liyiorg** [comment]
已发布2.8.7 版本，问题已修复。

**Comment by DemonTang** [comment]
@liyiorg 我maven中的版本改为2.8.7然后没有版本似的。是不是还没放到maven的中央仓库去

**Comment by liyiorg** [comment]
已提交到了中央仓库，会有大约一天的同步时间。
