### ISSUE TITLE
initMchKeyStore能支持文件流作为参数传入吗？

### ISSUE THREAD

**Issue by yf-sky** [liyiorg/weixin-popular#70]
您好，我们公司有多个微信公众号，所以退款证书有多个，如果使用路径保存的话，需要在项目之外用到文件系统，所以我们计划把证书转换为流保存到数据库中，但是您提供的初始化接口中不包括传入流形式的证书，请问您能更新这块的代码吗？
由于我没有找到该项目提交merge request的地方，我在本地写了一段修改过的代码，如下：
/**
     * 初始化   MCH HttpClient KeyStore
     *
     * @param mch_id           mch_id
     * @param keyStoreFilePath keyStoreFilePath
     */
    public static void initMchKeyStore(String mch_id, String keyStoreFilePath)  {
        try {
            FileInputStream instream = new FileInputStream(new File(keyStoreFilePath));
            initMchKeyStore(mch_id, instream);
            instream.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /**
     * 初始化   MCH HttpClient KeyStore
     *
     * @param mch_id   mch_id
     * @param instream instream
     */
    public static void initMchKeyStore(String mch_id, FileInputStream instream) {
        try {
            KeyStore keyStore = KeyStore.getInstance("PKCS12");
            keyStore.load(instream, mch_id.toCharArray());
            CloseableHttpClient httpClient = HttpClientFactory.createKeyMaterialHttpClient(keyStore, mch_id, timeout, retryExecutionCount);
            httpClient_mchKeyStore.put(mch_id, httpClient);
        } catch (KeyStoreException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (CertificateException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

**Comment by liyiorg** [comment]
已发布 2.8.7  版本，支持inputStream 参数。

**Comment by yf-sky** [comment]
谢谢啊！！赞！！
