### ISSUE TITLE
小程序二维码接口返回数据格式错误

### ISSUE THREAD

**Issue by CodinngLee** [liyiorg/weixin-popular#72]
小程序二维码的接口返回应该是一个图片字节流！

**Comment by liyiorg** [comment]
下版本修复为 BufferedImage

你先试用下，以下代码是否可用?

/**
	 * 获取小程序页面二维码 (beta)
	 * @since 2.8.5
	 * @param access_token access_token
	 * @param wxaqrcode wxaqrcode
	 * @return result
	 */
	public static BufferedImage wxaappCreatewxaqrcode(String access_token,Wxaqrcode wxaqrcode){
		String json = JsonUtil.toJSONString(wxaqrcode);
		HttpUriRequest httpUriRequest = RequestBuilder.post()
								.setHeader(jsonHeader)
								.setUri(BASE_URI + "/cgi-bin/wxaapp/createwxaqrcode")
								.addParameter(PARAM_ACCESS_TOKEN, API.accessToken(access_token))
								.setEntity(new StringEntity(json,Charset.forName("utf-8")))
								.build();
		CloseableHttpResponse httpResponse = LocalHttpClient.execute(httpUriRequest);
		try {
			int status = httpResponse.getStatusLine().getStatusCode();
            if (status == 200) {
				byte[] bytes = EntityUtils.toByteArray(httpResponse.getEntity());
				return ImageIO.read(new ByteArrayInputStream(bytes));
            }
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				httpResponse.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		return null;
	}

**Comment by CodinngLee** [comment]
好的

**Comment by CodinngLee** [comment]
可以读取到二维码了

**Comment by CodinngLee** [comment]
其实直接返回byte[]来更好

**Comment by liyiorg** [comment]
对于一般文件流来说，直接返回byte[] 会更好点，图片流包装成BufferedImage的话，使用ImageIO 可以直接输出显示，也可以保存，代码编写会更简便点。
