### ISSUE TITLE
统一下单detail处理为"null"字符串，detail为空时，会造成签名签名错误

### ISSUE THREAD

**Issue by mnshun** [liyiorg/weixin-popular#73]
解决方案
weixin.popular.util.MapUtil
/**
	 * url 参数串连
	 * @param map map
	 * @param keyLower keyLower
	 * @param valueUrlencode valueUrlencode
	 * @return string
	 */
	public static String mapJoin(Map<String, String> map,boolean keyLower,boolean valueUrlencode){
		StringBuilder stringBuilder = new StringBuilder();
		for(String key :map.keySet()){
			if(map.get(key)!=null&&!"".equals(map.get(key))&&!"null".equals(map.get(key))){
//		    if(map.get(key)!=null&&!"".equals(map.get(key))){
				try {
					String temp = (key.endsWith("_")&&key.length()>1)?key.substring(0,key.length()-1):key;
					stringBuilder.append(keyLower?temp.toLowerCase():temp)
								 .append("=")
								 .append(valueUrlencode?URLEncoder.encode(map.get(key),"utf-8").replace("+", "%20"):map.get(key))
								 .append("&");
				} catch (UnsupportedEncodingException e) {
					e.printStackTrace();
				}
			}
		}
		if(stringBuilder.length()>0){
			stringBuilder.deleteCharAt(stringBuilder.length()-1);
		}
		return stringBuilder.toString();
	}

**Comment by liyiorg** [comment]
下版本修复

**Comment by liyiorg** [comment]
你试下最新版本
2.8.7

**Comment by liyiorg** [comment]
已发布2.8.8 ，问题已修复

**Comment by jingdongWang92** [comment]
大神，签名错误怎么解决啊。  参数什么的都没有问题，但是一直报签名错误
![image](https://cloud.githubusercontent.com/assets/14922915/25415917/5eef72e6-2a6d-11e7-8248-9fbfcd0dd522.png)

**Comment by jingdongWang92** [comment]
![image](https://cloud.githubusercontent.com/assets/14922915/25415927/77402930-2a6d-11e7-9c62-731666df725c.png)

**Comment by liyiorg** [comment]
@jingdongWang92  你那边使用版本是最新的 2.8.8 吗

**Comment by liyiorg** [comment]
你可以尝试将 weixin-popular 在pom.xml 文件的依赖位置放到最前面，以避免其自身依赖的jar 包版本号不对。
