### ISSUE TITLE
微信js_sdk域名配置，怎么解决多系统、多域名的白名单。

### ISSUE THREAD

**Issue by mnshun** [liyiorg/weixin-popular#74]

**Comment by liyiorg** [comment]
微信JS只可以配置三个域名,并要求在对应的根目录下放置txt 文件。域名可以是根域名也可以是子域名，如果要配置多个子域名怎么办呢？
可以按以下方式配置，只在微信后台配置根域名  mydomain.com, 然后将下载的txt 文件放到 （mydomain.com , www.mydomain.com, other1.mydomain.com , other2.mydomain.com ....）根目录下即可，这样子域名也是可以使用的。
