### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: server certificate change is restricted during renegotiation

### ISSUE THREAD

**Issue by dodoqumy** [liyiorg/weixin-popular#78]
HttpClient v4.3.6版本貌似有个关于SSLv3的bug，能否升级一下weixin-popular的依赖呢

> ... update HttpClient to a more recent version than 4.3.6, then SSLv3 will be disabled by default and your code should no longer report such exception.

[http://stackoverflow.com/questions/27105004/what-means-javax-net-ssl-sslhandshakeexception-server-certificate-change-is-re](url)

**Comment by liyiorg** [comment]
目前官方没有 4.3.x 的更新版，4.4.x   4.5.x 的版本需要测试。
