### ISSUE TITLE
提交一个MCH退款申请的改进

### ISSUE THREAD

**Issue by fancool** [liyiorg/weixin-popular#8]
这个问题不知道是我使用API的问题, 还是的确你们没有注意到, 在MCH退款申请的时候需要双向HTTPS双向认证, 其中还会用到私钥文件.

不知道这里怎么代码格式化, 请自行复制再修改

修改如下(建议)
在HttpClientFactory增加如下方法(此方法为官方文档中的代码)

       public static CloseableHttpClient createSslHttpClient() {
		KeyStore keyStore;
		try {
			keyStore = KeyStore.getInstance("PKCS12");
			FileInputStream instream = new FileInputStream(new File(WxwebConfig.PKCS12_FILE));//这里是私钥文件
			try {
				keyStore.load(instream, WxwebConfig.MCH_ID.toCharArray());
			} finally {
				instream.close();
			}
			SSLContext sslcontext = SSLContexts
					.custom()
					.loadKeyMaterial(keyStore, WxwebConfig.MCH_ID.toCharArray())
					.build();
			SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(
					sslcontext,
					new String[] { "TLSv1" },
					null,
					SSLConnectionSocketFactory.BROWSER_COMPATIBLE_HOSTNAME_VERIFIER);
			CloseableHttpClient httpclient = HttpClients.custom()
					.setSSLSocketFactory(sslsf).build();
			return httpclient;
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

在进行退款申请的时候要用此方法构建CloseableHttpClient , 大致代码如下
/**
	 * 退款申请
	 *
	 * 注意：
	 *	1.交易时间超过1 年的订单无法提交退款；
	 *	2.支持部分退款，部分退需要设置相同的订单号和不同的out_refund_no。一笔退款失
	 *	败后重新提交，要采用原来的out_refund_no。总退款金额不能超过用户实际支付金额。
	 * @param secapiPayRefund
	 * @param key 商户支付密钥
	 * @return
	 */

	public static SecapiPayRefundResult secapiPayRefund(SecapiPayRefund secapiPayRefund,String key){
		Map<String,String> map = MapUtil.objectToMap( secapiPayRefund);
		String sign = SignatureUtil.generateSign(map,key);
		secapiPayRefund.setSign(sign);
		String secapiPayRefundXML = XMLConverUtil.convertToXML( secapiPayRefund);
		HttpUriRequest httpUriRequest = RequestBuilder.post()
				.setHeader(xmlHeader)
				.setUri(MCH_URI + "/secapi/pay/refund")
				.setEntity(new StringEntity(secapiPayRefundXML,Charset.forName("utf-8")))
				.build();
                //此为原始代码
		//return LocalHttpClient.executeXmlResult(httpUriRequest,SecapiPayRefundResult.class);
                //此为建议更新的代码
		CloseableHttpClient hc = HttpClientFactory.createSslHttpClient();
		try {
			return ((SecapiPayRefundResult) hc.execute(httpUriRequest, XmlResponseHandler.createResponseHandler(SecapiPayRefundResult.class)));
		} catch (ClientProtocolException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}

**Comment by liyiorg** [comment]
感谢您的反馈！
已提交更新，我没有MCH 账号，请进行测试！

设置API-MCH-KeyStore 说明
https://github.com/liyiorg/weixin-popular/wiki/%E8%AE%BE%E7%BD%AEAPI-MCH-KeyStore

**Comment by fantycool** [comment]
还没有测试新版本, 但退款查询都必须要使用相同的方方式, 所以退款查询部分也需要按照此修改
![image](https://cloud.githubusercontent.com/assets/10257126/5659637/93372f10-9750-11e4-88e6-55a255d27d3f.png)

**Comment by liyiorg** [comment]
已提交更新

**Comment by i319962** [comment]
嗯。这个我也发现了，把微信官方提供的调用 p12文件的代码加上了。
