### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/xml/bind/marshaller/CharacterEscapeHandler

### ISSUE THREAD

**Issue by joviqiao** [liyiorg/weixin-popular#84]
xml 工具把 object 转为xml的时候报错。

同时，xml工具我想把微信返回的xml直接转为 hashmap 是不支持的

**Comment by liyiorg** [comment]
XMLConverUtil.convertToXML()是基于JAXB ,所以对应的类需要有JAXB 的注解定义，参照 MchPayNotify。
XMLConverUtil.convertToMap() 可以将简单的xml 转换为Map
