### ISSUE TITLE
SnsAPI接口方法的请求方式

### ISSUE THREAD

**Issue by rangersltw** [liyiorg/weixin-popular#87]
例如oauth2AccessToken方法，用的是POST，官方目前是GET，这个会有问题吧。

**Comment by liyiorg** [comment]
可以使用的

**Comment by linzea** [comment]
Could not initialize class weixin.popular.api.SnsAPI 你好，为什么我调用这个方法会说我这个没有初始化呢` public static SnsToken oauth2AccessToken(String appId,String secret,String code){
        SnsToken snsToken = null;
        try {
            if (StringUtil.isNotEmpty(appId) && StringUtil.isNotEmpty(secret) && StringUtil.isNotEmpty(code)){
                snsToken = SnsAPI.oauth2AccessToken(appId, secret, code);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return snsToken;
    }`

**Comment by linzea** [comment]
Could not initialize class weixin.popular.api.SnsAPI 你好，为什么我调用这个方法会说我这个没有初始化呢
`public static SnsToken oauth2AccessToken(String appId,String secret,String code){ 
SnsToken snsToken = null; 
try {
 if (StringUtil.isNotEmpty(appId) && StringUtil.isNotEmpty(secret) && StringUtil.isNotEmpty(code)){ 
              snsToken = SnsAPI.oauth2AccessToken(appId, secret, code);
 }
 }catch (Exception e){ 
     e.printStackTrace();
 }
 return snsToken;
 }`

**Comment by linzea** [comment]
你好，我遇到一个问题，在我调用这个类里面的方法的时候，他给我报了一个错误，我是这么用的
snsToken = SnsAPI.oauth2AccessToken(appId, secret, code);
nested exception is java.lang.NoClassDefFoundError: Could not initialize class weixin.popular.api.SnsAPI

**Comment by linzea** [comment]
你好，我遇到一个问题，在我调用这个类里面的方法的时候，他给我报了一个错误，我是这么用的
snsToken = SnsAPI.oauth2AccessToken(appId, secret, code);
nested exception is java.lang.NoClassDefFoundError: Could not initialize class weixin.popular.api.SnsAPI

**Comment by liyiorg** [comment]
可能 是环境，jdk 版本问题。
