### ISSUE TITLE
sign和body都有CDATA标签，是什么原因导致的？

### ISSUE THREAD

**Issue by llade** [liyiorg/weixin-popular#95]
![mza 9gzroj 97mxb vk ox](https://user-images.githubusercontent.com/1262532/28049465-24ea78ea-662a-11e7-8f3d-f5b0f43b70e4.png)
sign和body都有CDATA标签，是什么原因导致的？

**Comment by liyiorg** [comment]
weixin.popular.bean.paymch.Unifiedorder

        @XmlElement
	@XmlJavaTypeAdapter(value = AdaptorCDATA.class)
	private String sign;

**Comment by llade** [comment]
tks,查过，wechat api 支持CDATA的解析的。这边出错的原因是客户把appscret当成商户平台的key了。误报
